// Per-task REFER awareness for the estimator.
//
// HoneyDone is an insured Florida handyman, NOT a licensed contractor. Some
// rate-book tasks are licensed-trade or permit work (real electrical, plumbing
// beyond a simple swap, HVAC install, roofing, structural). The rate override
// layer only stores price/unit/labor/material, so the regulated status lives
// here, in src/data/refer_flags.json (generated by the ratebook pricing run).
//
// The estimator already enforces the $2,500 job cap from the system prompt, but
// that does not catch a regulated task that happens to price UNDER $2,500 (a
// water heater, a mini-split). This block gives the estimator the per-task
// referral list so it flags those out instead of quoting them as handyman work.
//
// Pure + server-side: a static JSON import, no prisma, no next.

import referData from "@/data/refer_flags.json";

export type ReferLevel = "REFER" | "VERIFY";

interface ReferRow {
  name: string;
  category: string;
  note: string;
}

const MAP: Map<string, { level: ReferLevel; note: string; category: string }> = (() => {
  const m = new Map<string, { level: ReferLevel; note: string; category: string }>();
  for (const r of referData.refer as ReferRow[]) m.set(r.name, { level: "REFER", note: r.note, category: r.category });
  for (const r of referData.verify as ReferRow[]) m.set(r.name, { level: "VERIFY", note: r.note, category: r.category });
  return m;
})();

/** REFER (licensed + permit), VERIFY (gray, confirm), or null (handyman-legal). */
export function referLevel(name: string): ReferLevel | null {
  return MAP.get(name)?.level ?? null;
}

/**
 * Build the estimator prompt block for the regulated tasks among `tasks`. Scales
 * with the tasks passed in (Local gets only the message-relevant ones, Claude
 * gets the full book), mirroring formatPricedBookForPrompt. Returns "" when none
 * of the tasks are regulated.
 */
export function formatReferFlagsForPrompt(tasks: { name: string }[]): string {
  const seen = new Set<string>();
  const refer: string[] = [];
  const verify: string[] = [];
  for (const t of tasks) {
    const hit = MAP.get(t.name);
    if (!hit || seen.has(t.name)) continue;
    seen.add(t.name);
    if (hit.level === "REFER") refer.push(`  - ${t.name}: ${hit.note}`);
    else verify.push(`  - ${t.name}: ${hit.note}`);
  }
  if (refer.length === 0 && verify.length === 0) return "";

  let out =
    "\n\nRegulated work (HoneyDone is an insured Florida handyman, NOT a licensed contractor). " +
    "The rate-book tasks below are licensed-trade or permit work. When the requested job matches one of these, do NOT quote it as normal handyman work, even if the price is under $2,500. " +
    "Leave it out of the priced scope and tell the client in your reply that it needs a licensed pro plus a permit, and that HoneyDone can coordinate a licensed sub. Never call HoneyDone a contractor.";
  if (refer.length) out += `\nRefer out (licensed trade + permit required):\n${refer.join("\n")}`;
  if (verify.length)
    out += `\nConfirm scope on site, and refer out if it involves new wiring, a permit, or structural or load-bearing work:\n${verify.join("\n")}`;
  return out;
}
