// Per-line "how it gets done" steps.
//
// When Manny expands a line, the card shows the ordered work steps a crew would
// run for that line, plus a one-line rationale that ties the quantity or hours
// to the scope. That is how he sees the reasoning behind the number, not just
// the arithmetic. Generated by Claude server-side, with a deterministic
// keyword fallback so it still works offline.

import type { LineItem } from "./types";
import { HONEYDONE } from "./honeydone";

export interface StepsResult {
  steps: string[];
  rationale?: string;
}

export const STEPS_SYSTEM = `You explain how a single line of work on a HoneyDone Property Maintenance estimate actually gets done, so the estimator can see the reasoning behind the number. HoneyDone is an insured Florida handyman and property maintenance service (not a licensed contractor). Labor is billed at $${HONEYDONE.laborRate}/hr.

Given one line item, return the ordered installation or work steps a crew would perform, start to finish. Cover demo, prep, the core work, and cleanup when they apply. Keep each step short, a phrase or one plain sentence in shop language. Three to seven steps is usually right.

Also return a one line rationale that ties the quantity or hours to the scope, so it is clear why the line is sized the way it is.

No em dashes and no semicolons. Emit through the build_steps tool.`;

export const BUILD_STEPS_TOOL = {
  name: "build_steps",
  description: "Return the ordered work steps and a sizing rationale for one estimate line.",
  input_schema: {
    type: "object" as const,
    properties: {
      steps: { type: "array", items: { type: "string" }, description: "Ordered work steps.", minItems: 2 },
      rationale: { type: "string", description: "One line tying quantity or hours to scope." },
    },
    required: ["steps"],
  },
};

export function stepsUserTurn(item: LineItem, estimateName: string): string {
  const sup = item.supplier ? `\nSupplier: ${item.supplier}` : "";
  return `Estimate: ${estimateName}
Line item: ${item.name}
Quantity: ${item.quantity} ${item.unit}
Cost type: ${item.costType}
Unit cost: $${item.unitCost}${sup}

Give the ordered work steps for this line and a one line sizing rationale.`;
}

/** Keyword-based fallback used offline or if the model call fails. */
export function deterministicSteps(item: LineItem): StepsResult {
  const n = item.name.toLowerCase();
  const steps: string[] = [];
  const add = (...s: string[]) => steps.push(...s);

  if (/trip charge|mobiliz/.test(n)) {
    add("Load tools and materials", "Drive to the job site", "Stage and protect the work area");
  } else if (/dumpster|haul|disposal|debris|cleanup|clean-up/.test(n)) {
    add("Gather and bag all debris", "Load the haul vehicle or dumpster", "Sweep and leave the area clean");
  } else if (/demo|tear-out|tear out|remove/.test(n)) {
    add("Protect surrounding finishes", "Remove the existing material", "Bag debris and inspect what is behind it");
  } else if (/fascia|soffit|drip edge|rot|framing|carpentry/.test(n)) {
    add(
      "Remove the deteriorated boards and old flashing",
      "Repair or replace any rotted framing",
      "Cut and dry-fit the new boards",
      "Fasten with exterior rated screws",
      "Install drip edge and flashing",
      "Caulk and seal all joints"
    );
  } else if (/drywall|patch|sheetrock/.test(n)) {
    add("Cut out the damaged section", "Set backing and fit new board", "Tape, mud, and feather the joints", "Sand smooth and match the texture");
  } else if (/paint|prime/.test(n)) {
    add("Mask and protect adjacent surfaces", "Prime bare or patched areas", "Apply the finish coats", "Pull masking and touch up");
  } else if (/grout|caulk|tile|silicone/.test(n)) {
    add("Grind out failed grout and old caulk", "Clean and dry the joints", "Apply new grout", "Tool fresh silicone at the seams");
  } else if (/pressure wash|power wash|seal/.test(n)) {
    add("Pre-treat the surface", "Pressure wash evenly", "Let it dry fully", "Apply sealer where included");
  } else if (/install|set |mount|hang|replace|fixture|toilet|vanity|faucet|door/.test(n)) {
    add("Remove or prep the existing unit", "Dry-fit the new unit", "Secure and connect it", "Test and clean up");
  } else {
    add("Prep the work area", "Perform the work as described", "Clean up and remove debris");
  }

  let rationale: string;
  if (item.costType === "Labor") {
    rationale = `${item.quantity} ${item.unit} of skilled labor at $${item.unitCost}/hr for the scope above.`;
  } else if (item.costType === "Material") {
    rationale = `${item.quantity} ${item.unit} of material to cover the work, priced at cost plus the shop markup.`;
  } else {
    rationale = `${item.quantity} ${item.unit} flat for this line.`;
  }
  return { steps, rationale };
}
